#server:
#  port: 8090


spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  profiles: dev

  # Spring Boot 실행시 BATCH 자동 실행 못하게 설정
  batch:
    initialize-schema: never
    job:
#      names: ${job.name:NONE}
      enabled: true
  cloud:
    task:
      initialize-enabled: false
      batch:
        fail-on-job-failure: true

  datasource:
    hikari:
      main:
        jdbc-url: jdbc:postgresql://10.87.190.210:5432/postgres
        pool-name: hikari-cp
        maximum-pool-size: 30
        minimum-idle: 2
        driver-class-name: org.postgresql.Driver
        username: postgress
        password: postgresspw123!
      hobis:
        jdbc-url: jdbc:oracle:thin:@192.168.88.199:13042/DB19HNID5
        pool-name: hikari-cp
        maximum-pool-size: 30
        minimum-idle: 2
        driver-class-name: oracle.jdbc.OracleDriver
        username: HNIDADM
        password: hndbam19924
  jpa:
    hibernate:
      ddl-auto: none  # 없으면 만들고 있으면 그대로 사용
#    properties:
#      hibernate:
#        show_sql: true                #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
#        format_sql: true              #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
#        use_sql_comments: true        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.


kafka:
  bootstrap:
    server: 10.25.90.115:9092,10.25.90.115:9093,10.25.90.115:9094

#
logging:
  level:
    com:
      tifscore: debug

oneqclient:
  clientId: UAT-1QBatch-LOAN
  clientSecret: pQoOGZV/E/CvHcsy3Z99TOFxnRwogS3daf6VgCn9xq0=

batch:
  timeznoe: Asia/Jakarta
  onlineIp: http://10.87.190.9:18000/ #UAT